In [30]:
import numpy as np  ## Mengimpor library NumPy dengan alias np
twoDArray = np.array([[11, 15, 10, 6],
                      [10, 14, 11, 5],
                      [12, 17, 12, 8],
                      [15, 18, 14, 9]])  ## Membuat array 2 dimensi (4x4)
print(twoDArray)  ## Menampilkan isi array

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [31]:
import numpy as np  ## Mengimpor library NumPy
newTwoDArray = np.insert(twoDArray, 1, [[1,2,3,4]], axis=0)  ## Menyisipkan baris baru [1,2,3,4] ke dalam twoDArray pada index ke-1 (baris kedua),
                                                             ## axis=0 berarti baris

print(newTwoDArray)  ## Menampilkan array yang sudah ditambahkan baris baru

[[11 15 10  6]
 [ 1  2  3  4]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [32]:
import numpy as np  ## Mengimpor library NumPy
print(len(twoDArray))  ## Menghitung jumlah baris pada array 2 dimensi (panjang array utama)

4


In [33]:
import numpy as np  ## Mengimpor library NumPy
newTwoDArray = np.append(twoDArray, [[1,2,3,4]], axis=0)  ## Menambahkan baris baru [1,2,3,4] di akhir twoDArray,
                                                          ## axis=0 berarti menambah sebagai baris

print(newTwoDArray)  ## Menampilkan array yang sudah ditambahkan baris baru

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]
 [ 1  2  3  4]]


In [34]:
import numpy as np  ## Mengimpor library NumPy
print(len(newTwoDArray))  ## Menghitung jumlah baris pada array baru (setelah penambahan data)

5


In [35]:
import numpy as np  ## Mengimpor library NumPy
print(len(newTwoDArray[0]))  ## Menghitung jumlah elemen (kolom) pada baris pertama array

4


In [36]:
import numpy as np  ## Mengimpor library NumPy
def accessElements(array, rowIndex, colIndex):  ## Membuat fungsi untuk mengakses elemen array berdasarkan indeks
    if rowIndex >= len(array) or colIndex >= len(array[0]):  ## Mengecek apakah indeks melebihi batas array
        print('Incorrect Index')  ## Menampilkan pesan jika indeks tidak valid
    else:
        print(array[rowIndex][colIndex])  ## Menampilkan nilai elemen sesuai baris dan kolom yang diminta

In [37]:
import numpy as np  ## Mengimpor library NumPy
accessElements(newTwoDArray, 3, 1)  ## Memanggil fungsi untuk mengambil elemen pada baris ke-3 dan kolom ke-1

18


In [38]:
import numpy as np  ## Mengimpor library NumPy
def traverseTDArray(array):  ## Membuat fungsi untuk menelusuri (traverse) seluruh elemen array 2D
    for i in range(len(array)):  ## Loop untuk setiap baris
        for j in range(len(array[0])):  ## Loop untuk setiap kolom
            print(array[i][j])  ## Menampilkan setiap elemen array satu per satu

In [39]:
import numpy as np  ## Mengimpor library NumPy
traverseTDArray(twoDArray)  ## Memanggil fungsi untuk menampilkan semua elemen dalam array 2D satu per satu

11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


In [40]:
import numpy as np  ## Mengimpor library NumPy
def searchTDArray(array, value):  ## Membuat fungsi untuk mencari nilai dalam array 2D
    for i in range(len(array)):  ## Loop untuk setiap baris
        for j in range(len(array[0])):  ## Loop untuk setiap kolom
            if array[i][j] == value:  ## Mengecek apakah nilai sama dengan yang dicari
                return 'The value is located index '+str(i)+" "+str(j)  ## Mengembalikan posisi indeks jika ditemukan
    return 'The element no found'  ## Mengembalikan pesan jika nilai tidak ditemukan

In [41]:
import numpy as np  ## Mengimpor library NumPy
print(twoDArray)  ## Menampilkan isi array 2D ke layar

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [42]:
import numpy as np  ## Mengimpor library NumPy
print(searchTDArray(twoDArray, 11))  ## Memanggil fungsi pencarian untuk mencari nilai 11 dalam array, lalu menampilkan hasilnya

The value is located index 0 0


In [43]:
import numpy as np  ## Mengimpor library NumPy
newTDArray = np.delete(twoDArray, 1, axis=0)  ## Menghapus baris pada index ke-1 (baris kedua) dari array, axis=0 berarti operasi pada baris
print(newTDArray)  ## Menampilkan array setelah baris dihapus

[[11 15 10  6]
 [12 17 12  8]
 [15 18 14  9]]


In [44]:
import numpy as np  ## Mengimpor library NumPy
print(twoDArray)  ## Menampilkan isi array asli (tidak berubah setelah operasi delete karena hasil disimpan di variabel baru)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
